# Generated by Django 5.0.2 on 2024-02-22 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='matrix_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
    ]
